language: rust
rust:
  - stable
cache: cargo
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile
  - rustup component add clippy
script:
  - cargo audit
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --release
