language: rust
rust:
  - stable
  - nightly
cache: cargo
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qt5-default qttools5-dev-tools
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
        rustup component add clippy
      fi
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo clippy --all-targets --all-features -- -D warnings
    fi
  - QT_DIR=/usr/local/opt/qt cargo test --release
