[package]
name = "qrcode-cli"
version = "0.7.0"
authors = ["Leonid Beder <leonid.beder@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
qrcode = "0.12.0"
strum = "0.20.0"
strum_macros = "0.20.1"
svgdom = "0.18.0"
resvg = "0.11.0"

[dev-dependencies]
quirc = "0.0.1"
tempfile = "3.1.0"
image = "0.23.12"
usvg = "0.11.0"
