[package]
name = "qrcode-cli"
version = "0.1.0"
authors = ["Leonid Beder <leonid.beder@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
qrcode = "0.8"
hex = "0.3.1"
image = "0.21.0"
strum = "0.13.0"
strum_macros = "0.13.0"
