[package]
name = "qrcode-cli"
version = "0.3.1"
authors = ["Leonid Beder <leonid.beder@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
qrcode = "0.8"
hex = "0.3.1"
strum = "0.13.0"
strum_macros = "0.13.0"
svgdom = "0.16.0"

[dev-dependencies]
quirc = "0.0.1"
tempfile = "3.0.7"
image = "0.19.0"

[dev-dependencies.resvg]
version = "0.5.0"
features = ["qt-backend"]
