[package]
name = "qrcode-cli"
version = "0.3.3"
authors = ["Leonid Beder <leonid.beder@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2"
qrcode = "0.8"
hex = "0.3.2"
strum = "0.15.0"
strum_macros = "0.15.0"
svgdom = "0.16.1"

[dev-dependencies]
quirc = "0.0.1"
tempfile = "3.0.7"
image = "0.21.1"

[dev-dependencies.resvg]
version = "0.6.1"
features = ["qt-backend"]
